# .github/workflows/release.yml

name: Release

# push 到 main 分支時，會促發此 workflow
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    environment: release # 這裡要記得指定套用的環境，才能取得變數
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - name: Install modules
        run: pnpm install
#      - name: Install dependencies
#        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx semantic-release
      - name: 发布NPM包
        # 执行发布代码
        run: |
          pnpm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          pnpm publish
        env:
          # 配置 npm access token 环境变量
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
